### PR TITLE
Use Python 3.9 and newer linphone sdk

### PR DESCRIPTION
**Pull request by sopelj**
https://wazo-dev.atlassian.net/browse/WAZO-3246

### CODE REVIEW

**Comment by DrPyser** [comment]
recheck

**Comment by DrPyser** [comment]
https://wazo-dev.atlassian.net/browse/WAZO-3246

**Review by pc-m — DISMISSED** [review]

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
Blocked until we test a run in acceptance with zuul (open new pr and link this one)

**Comment by fblackburn1** [comment]
Oh wow, since the base branch has been deleted, the whole PR has been closed .... :persevere:

**Pull request closed without merging**
